version: '2'
services:
  phidget-network-server:
    build: phidget-network-server
    ports:
      - "8989"
    network_mode: host
    privileged: true
    restart: always
    labels:
      io.balena.features.kernel-modules: true
